name: Manual Trigger
on:
    workflow_dispatch: # 手動実行イベント
        inputs: # 入力パラメータの定義
            greeting: # パラメータ名
                type: string # パラメータの型
                description: 'An example input parameter' # 説明
                required: true # 必須かどうか
                default: 'default value' # デフォルト値
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ inputs.greeting }}"